CID-2910: Proxy support
leanix/leanix-github-agent pull request #55
Opened 2024-11-25 14:40 UTC by mohamedlajmileanix

## 🛠 Changes made
Documentation update, after validation of proxy support.

## ✨ Type of change
- [x] Documentation update

## 🧪 How Has This Been Tested?
- [x] 🚨 No tests Deployed

## 🏎 Checklist:
- [x] I have made corresponding changes to the documentation (README.md)
- [x] My commit message clearly reflects the changes made
- [x] Assigned the appropriate labels (version, PR type, etc.)

2024-11-26 16:12 UTC, ana-dashuk-leanix requested changes

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +Add the following properties on the command:
```suggestion
#### Using an HTTP Proxy System

Add the following properties to the command:
```

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +> Note: Basic authentication is not currently supported.
```suggestion
> **Note:** Basic authentication is not currently supported.
```

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +#### Using over SSL Intercepting proxy
```suggestion
#### Using an SSL Intercepting Proxy
```

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +> Note: You should add an additional COPY and the final RUN for each certificate you need to insert into the image.
```suggestion
> **Note:** Add an additional COPY and the final RUN for each certificate you need to insert into the image.
```

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +Build your own docker image adding the certificate:
```suggestion
Build your own Docker image by adding the certificate:
```

2024-11-26 16:12 UTC, ana-dashuk-leanix commented on README.md
> +Just run the container by providing the following command:
```suggestion
#### Using AMD64 Images on Apple M1

Run the container by providing the following command:
```

2024-11-28 08:38 UTC, alfredo-mfaria approved these changes

2024-11-28 08:54 UTC, ana-dashuk-leanix approved these changes

2024-12-02 08:29 UTC, merged